---
- hosts: key_prajjwalkey # Please change this key based on what you have used to create instances.
  user: ubuntu
  sudo: yes
  vars:
    Env_Name: "{{ ENVR }}"
  vars_files:
       - vars
  tasks:
    - include: tasks.yml
